const modelSchemas = {
  attendace: {
    attendaceId: "String",
    employeeId: "String",
    datetime: "Date",
    note: "String",
  },
  auth: {
    authId: "String",
    email: "String",
    password: "String",
    roleId: "String",
    employeeId: "String",
    status: "String",
  },
  authLog: {
    id: "String",
    authId: "String",
    method: "String",
    url: "String",
    status: "Int",
    responseTime: "Float",
    ip: "String",
    userAgent: "String",
  },
  cart: {
    cartId: "String",
    authId: "String",
    userId: "String",
    productId: "String",
    quantity: "Int",
    status: "String",
  },
  cartNote: {
    noteId: "String",
    cartId: "String",
    note: "String",
  },
  category: {
    categoryId: "String",
    picture: "String",
    categoryName: "String",
    categoryCode: "String",
    memo: "String",
    status: "String",
  },
  customer: {
    customerId: "String",
    firstName: "String",
    lastName: "String",
    gender: "String",
    phone: "String",
    status: "String",
    employeeId: "String",
  },
  customerinfo: {
    customerId: "String",
    picture: "String",
    region: "String",
    email: "String",
    note: "String",
    govId: "String",
    povPicture: "String",
    govExpire: "DateTime",
    status: "String",
  },
  department: {
    departmentId: "String",
    departmentName: "String",
    departmentCode: "String",
    memo: "String",
    status: "String",
  },
  employee: {
    employeeId: "String",
    employeeCode: "String",
    firstName: "String",
    lastName: "String",
    gender: "String",
    dob: "DateTime",
    phone: "String",
    positionId: "String",
    departmentId: "String",
    salary: "Int",
    hiredDate: "DateTime",
    status: "String",
  },
  employeeInfo: {
    infoId: "String",
    employeeId: "String",
    picture: "String",
    region: "String",
    email: "String",
    address: "String",
    cityId: "String",
    stateId: "String",
    country: "String",
    note: "String",
  },
  groupMessage: {
    groupMessageId: "String",
    authId: "String",
    content: "String",
    time: "Date",
  },
  log: {
    id: "String",
    method: "String",
    url: "String",
    status: "Int",
    responseTime: "Float",
    ip: "String",
    userAgent: "String",
  },
  notification: {
    notificationId: "String",
    authId: "String",
    title: "String",
    content: "String",
  },
  payment: {
    paymentId: "String",
    employeeId: "String",
    saleId: "String",
    reservationId: "String",
    invoice: "String",
    hash: "String",
    fromAccountId: "String",
    toAccountId: "String",
    currency: "String",
    amount: "Decimal",
    externalRef: "String",
    status: "String",
  },
  position: {
    positionId: "String",
    departmentId: "String",
    positionName: "String",
    positionCode: "String",
    memo: "String",
    status: "String",
  },
  product: {
    productId: "String",
    productName: "String",
    productCode: "String",
    categoryId: "String",
    picture: "String",
    unit: "String",
    capacity: "String",
    sellPrice: "Decimal",
    costPrice: "Decimal",
    discountRate: "Int",
    status: "String",
    desc: "String",
  },
  category: {
    productCategoryId: "String",
    picture: "String",
    categoryName: "String",
    categoryCode: "String",
    memo: "String",
    status: "String",
  },
  productStock: {
    productStockId: "String",
    productId: "String",
    supplierId: "String",
    invNumber: "String",
    productAdd: "Int",
    addPrice: "Decimal",
    addDate: "Date",
    memo: "String",
    status: "String",
  },
  role: {
    roleId: "String",
    name: "String",
  },
  sale: {
    saleId: "String",
    employeeId: "String",
    customerId: "String",
    saleDate: "Date",
    amount: "Decimal",
    picture: "String",
    memo: "String",
    status: "String",
  },
  saleDetail: {
    saleDetailId: "String",
    saleId: "String",
    productId: "String",
    quantity: "Int",
    amount: "Decimal",
  },
  shift: {
    shiftId: "String",
    authId: "String",
    shiftCode: "String",
    openKhmerRiel: "Decimal",
    openUsDollar: "Decimal",
    openTime: "Date",
    closeKhmerRiel: "Decimal",
    closeUsDollar: "Decimal",
    closeTime: "Date",
    status: "String",
  },
  supplier: {
    supplierId: "String",
    supplierName: "String",
    companyName: "String",
    phone: "String",
    email: "String",
    address: "String",
    status: "String",
    createdAt: "Date",
  },
};

module.exports = { modelSchemas };
